### ISSUE TITLE
getCommentReplies does not work correctly

### ISSUE THREAD

**Issue by chdzma** [GilgusMaximus/yt-comment-scraper#17]
Hi, thanks for the work

I am trying to get the replies when the replyToken is informed, but it is giving me an error:

> TypeError: Cannot read property 'response' of undefined
>     at Function.getCommentReplies (/node_modules/yt-comment-scraper/src/Youtube-Scraper.js:69:55)
>     at runMicrotasks (<anonymous>)
>     at processTicksAndRejections (internal/process/task_queues.js:93:5)

The error is caught in the catch of getCommentReplies

My code:

```
const payload = {
    videoId: video.id,
    sortByNewest: true,
    setCookie: true
}

ytcm.getComments(payload).then((data) =>{
    const comments = data.comments;
    for (let index = 0; index < comments.length; index++) {
        let comment = comments[index];
 
        if (comment.replyToken) {
            ytcm.getCommentReplies(video.id, comment.replyToken).then((data) =>{
                console.log(data);
                comments[index].threads = data;
            }).catch((error)=>{
                console.log(error);
            });
        }
    }
    videoDetails['comments'] = comments;
}).catch((error)=>{
    console.log(error);
});
```

**Comment by GilgusMaximus** [comment]
Thanks for finding this issue. It was actually a commit a while back which apparently broke the standalone usage and no one has come around to this very obvious problem since then.

But a fix is already done. I will just start to add some unit-tests so this does not happen as easily again before I will push out a new release. But should be up to date in 1 / 2 days
